### ISSUE TITLE
Elaborer un Modèle conceptuel de données 

### ISSUE THREAD

**Issue by Vincent-Bulut** [Vincent-Bulut/CryptoBot#4]

**Comment by Torfyn** [comment]
Modèle de donné MCD : 

User : entité qui représente les utilisateurs de l'application. Entité qui contient des informations telles que l'identifiant, l'adresse e-mail, le mot de passe, le solde en devises, le solde en cryptomonnaies, etc.

Order : entité qui représente les ordres passés par les utilisateurs. Elle contient des informations telles que l'identifiant, le type d'ordre (achat ou vente), la quantité de cryptomonnaies, le prix, l'heure de création, l'état de l'ordre (en attente, exécuté, annulé, etc.), etc.

Transaction : entité qui représente les transactions effectuées par l'application. Elle contient des informations telles que l'identifiant, le type de transaction (achat ou vente), la quantité de cryptomonnaies, le prix, l'heure de création, l'utilisateur associé, etc.

Bot : entité qui représente le robot de trading de l'application. Elle contient des informations telles que l'identifiant, l'état du bot (activé ou désactivé), les paramètres de trading (stratégie, stop loss, take profit, etc.), l'utilisateur associé, etc.

Currency : entité qui représente les différentes devises et cryptomonnaies disponibles sur l'application. Elle contient des informations telles que l'identifiant, le nom, le symbole, le taux de change par rapport au dollar, etc.

Market : entité qui représente les différents marchés de trading disponibles sur l'application (par exemple, BTC/USD, ETH/USD, etc.). Elle contient des informations telles que l'identifiant, le nom, les devises associées, les heures d'ouverture et de fermeture, les frais de transaction, etc.

**Comment by Torfyn** [comment]
![image](https://user-images.githubusercontent.com/78826181/225633596-e90d359b-23c7-4537-9137-be89b7d23998.png)

**Comment by Vincent-Bulut** [comment]
Merci
Il faudrait idéalement rajouter les attributs des entités, définir les clés primaires ainsi que la cardinalité pour chaque relation.

**Comment by Data-T-EGNR** [comment]
Il faudra le avec toutes les entités? Là je suis en train de réfléchir seulement sur les currency et juste pour cette entité j'ai 3 tableaux en préparation.

**Comment by Data-T-EGNR** [comment]
*les attributs

**Comment by Vincent-Bulut** [comment]
Pour toutes les entités, les attributs seront les colonnes de la table.
Priorité : réfléchir sur une clé primaire pour chaque entité puis réfléchir aux relations qu'il y a entre les entités.
En fonction des cardinalités on pourra en déduire les clé étrangères pour chaque entité. 
=> Focus sur les clés, les attributs pas très importants à ce stade ;)

**Comment by Data-T-EGNR** [comment]
Pour mes tables, la clé primaire que j'ai choisi c'est "symbol" (ex : "BTCUSDT") vu que l'on est sur de l'investissement automatisé. Qu'en pensez vous? Vu que je suis encore sur la construction je peux changer.

**Comment by Vincent-Bulut** [comment]
symbol ça convient très bien en clé primaire pour la table Asset 
réfléchir à la suite, une table de prix avec les données historiques et de streaming ou deux tables l'une avec les données histo l'autre avec les données de streaming

**Comment by Data-T-EGNR** [comment]
👍 
Pour le ML j'ai pensé plutôt à deux tables historique et streaming. La table historique étant figée et la table streaming en augmentation régulière de donnée, je me dis que ça permettrait peut être d'améliorer la qualité d'analyse ...

**Comment by Vincent-Bulut** [comment]
Pour le diagramme il faut qu'il soit normalisé au format standard 
On pourrait s'inspirer de ceci par exemple :
https://www.prospection-ciblee.com/mcd-modele-conceptuel-de-donnees-base-de-donnees/

**Comment by Vincent-Bulut** [comment]
> 👍 Pour le ML j'ai pensé plutôt à deux tables historique et streaming. La table historique étant figée et la table streaming en augmentation régulière de donnée, je me dis que ça permettrait peut être d'améliorer la qualité d'analyse ...

Oui je suis d'accord splittons en deux tables

**Comment by Data-T-EGNR** [comment]
> Pour le diagramme il faut qu'il soit normalisé au format standard On pourrait s'inspirer de ceci par exemple : https://www.prospection-ciblee.com/mcd-modele-conceptuel-de-donnees-base-de-donnees/

Carrément, ça permet immédiatement de prendre des bonnes habitudes pour des futures mission en tant que Data Engineer en plus.
